### PR TITLE
Fix issue with interface in dnsmasq

### PR DESCRIPTION
**Pull request by alexAubin**
## Problem

- Several people reporting upgrade crash with dnsmasq displaying `dnsmasq: interface wlan0 inconnue`
- Dnsmasq may not like the fact that there is an `interface=wlanX` in its conf if the interface is not up

## Solution

- We don't need all the complex and weird templating ... YunoHost core already handles having `interface=wlanX` for all wireless interfaces that are up
- We should just need to call yunohost's regen-conf when starting/stopping the service

## PR Status

Yolo

### CODE REVIEW

**Comment by alexAubin** [comment]
!testme

**Comment by hidrarga** [comment]
Could you also remove the `/etc/dnsmasq.d/$app.conf` ? To be sure it's been removed

**Comment by alexAubin** [comment]
(Done)

**Comment by alexAubin** [comment]
!testme

**Pull request merged**
