### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by alexAubin**
- https://github.com/YunoHost-Apps/hotspot_ynh/pull/107
- https://github.com/YunoHost-Apps/hotspot_ynh/pull/106
- https://github.com/YunoHost-Apps/hotspot_ynh/pull/105

### CODE REVIEW

**Comment by alexAubin** [comment]
!testme

**Comment by hidrarga** [comment]
!testme

**Review by alexAubin — COMMENTED** [review]
LGTM then :grimacing: 

@hidrarga : do you see any items remaining you'd like to work on ?

**Comment by hidrarga** [comment]
Yes, I would like to test it further, because there are some issues with internet access yet (see also comments in #100). I didn't have time to figure out what is the issue exactly :/

**Comment by hidrarga** [comment]
I fixed the issue with DNS resolution !
I also noticed some weird merged stuff oO I cleaned up, but I hope I didn't miss anything…

There are still some details I would need to check when we have two wifi devices... But we can consider this feature as experimental anyways.

I'm okay if we merge like this :)

**Pull request merged**
